[package]
name = "moho-ipc-module"
version = "0.1.0"
edition = "2021"

[lib]
name = "moho_ipc"
crate-type = ["cdylib"]
path = "src/module.rs"

[dependencies]
anyhow = "1"
thiserror = "1"
tracing = "0.1"

[profile.release]
opt-level = 3
lto = true
